### PR TITLE
remove http:// form bbs api_location

### PR DESCRIPTION
**Pull request by mehtaphysical**
there should not be http here

### CODE REVIEW

**Comment by fordaz** [comment]
@mehtaphysical please sign the CLA for us to take a look at this. 

Thanks,
CF Routing Team.

**Comment by shalako** [comment]
@mehtaphysical We'd like to take your contribution but we require a CLA from your self or your employer. If your employer has submitted the CLA, all you need to do is publicize your membership on Github. If you'd prefer, we can make the change for you. Please let us know what you'd like to do.

**Comment by crhino** [comment]
Closing due to inactivity

**Comment by mehtaphysical** [comment]
@crhino this change has already been implemented. Should be Closing due to Done or something.

**Pull request closed without merging**
