### PR TITLE
Replace tabs with spaces (and fix indent) of YAML in code blocks

### PR DESCRIPTION
**Pull request by nota-ja**
In order to be viewed properly on GitHub.

### CODE REVIEW

**Comment by shashwathi** [comment]
@nota-ja

Thank you for submitting the PR. 

Regards
Shash

**Comment by shalako** [comment]
Although the sentiment that spaces are preferred over tabs is acknowledged, this commit actually broke the formatting for most of the YML blocks it changed.

**Comment by nota-ja** [comment]
Thank you for merging.

But I have one question.

@shalako, what do you mean with "broke the formatting"?

The right images in the following table are the rendered view of the README.md of my commit ( 966729c5256a37b1986bd1750b24f60126684b53 ).

The left images are the one of the previous commit ( a4287e8cfe6eeb54a00f1235620f632556c008f3 , the HEAD commit of `develop` branch when this pull request made) as well.

All of them were captured with Chrome 56.0.2924.87 (64-bit) on Mac.

| commit | a4287e8cfe6eeb54a00f1235620f632556c008f3 (older) | 966729c5256a37b1986bd1750b24f60126684b53 (this) |
|---|---|---|
| image |  |  |
| partially enlarged |  |  |

The last row contains enlarged images for each commit. I will use them for the following explanation.

As you see in [this example deployment manifest](https://github.com/cloudfoundry/cf-release/blob/eb70def995d9108cfd91bb1050180c8c77db5f53/example_manifests/minimal-aws.yml#L1158-L1248), the right structure of the part of the YAML is:

* `properties`
  * `uaa`
    * `ssl`
      * `port`
    * `sslCertificate`
    * `sslPrivateKey`

However, the rendered view of the old commit is seen as:

* `properties`
  * `uaa`
* `ssl`
  * `port`
* `sslCertificate`
* `sslPrivateKey`

As I thought this was wrong, I made this pull request.
Actually the rendered view of my commit is seen as:

* `properties`
  * `uaa`
    * `ssl`
      * `port`
    * `sslCertificate`
    * `sslPrivateKey`

So I think my commit did not "break" the formatting.

**Comment by shalako** [comment]
I must have been looking at the wrong branch. Develop looks look. Thank you.

**Pull request merged**
